#project:
#  name: membership inference attack in federated learning
#  author: mingo

dataset:
  input_shape: [32, 32, 3]
  classes_num: 10

participant:
  learning_rate: 0.0001
  fed_epochs: 5
  local_epochs: 15
  clients_num: 4
  client_ratio_per_round: 1.00
  target_cid: 1
  target_fed_epoch: 4

attacker_participant:
  local_epochs: 100
  attacker_cid: 2

attacker_data_handler:
  batch_size: 32
  exposed_percentage: 100

inference_model:
  epochs: 10
  learning_rate: 0.0001
  exploited_layer_indexes: [6]
  exploited_gradient_indexes: [6]
  exploit_label: True
  exploit_loss: True
  optimizer_name: adam


